/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vaccineapp;

import java.util.ArrayList;

/**
 *
 * @author fitzg
 */
public class VaccineGUI extends javax.swing.JFrame {

    /**
     * Creates new form VaccineGUI
     */
        private PUInterface thePQueue;
       

        public VaccineGUI() {
        thePQueue = new PriorityQueue();
           initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pNamLbl = new javax.swing.JLabel();
        pNamTf = new javax.swing.JTextField();
        pAgeLbl = new javax.swing.JLabel();
        pAgeTf = new javax.swing.JTextField();
        mConLbl = new javax.swing.JLabel();
        mConTf = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        schedBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        extBtn = new javax.swing.JButton();
        pListBtn = new javax.swing.JButton();
        prioLbl = new javax.swing.JLabel();
        prioTf = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("Welcome to the Vaccine App");

        pNamLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pNamLbl.setText("Patients Name:");

        pAgeLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pAgeLbl.setText("Patients Age:");

        mConLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mConLbl.setText("Medical Condition (Y/N):");

        addBtn.setText("Add Patient");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        schedBtn.setText("Next Group");
        schedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schedBtnActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        extBtn.setText("Exit");
        extBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extBtnActionPerformed(evt);
            }
        });

        pListBtn.setText("List");
        pListBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pListBtnActionPerformed(evt);
            }
        });

        prioLbl.setText("Priority:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane1))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(104, 104, 104)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(pNamLbl)
                                        .addComponent(pAgeLbl))
                                    .addGap(66, 66, 66)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(pAgeTf, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(pNamTf, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(mConLbl)
                                        .addComponent(prioLbl))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(mConTf)
                                        .addComponent(prioTf))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(addBtn)
                                .addGap(18, 18, 18)
                                .addComponent(schedBtn)
                                .addGap(18, 18, 18)
                                .addComponent(pListBtn)
                                .addGap(18, 18, 18)
                                .addComponent(extBtn)))))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pNamLbl)
                    .addComponent(pNamTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pAgeLbl)
                    .addComponent(pAgeTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mConLbl)
                    .addComponent(mConTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prioLbl)
                    .addComponent(prioTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBtn)
                    .addComponent(schedBtn)
                    .addComponent(extBtn)
                    .addComponent(pListBtn))
                .addContainerGap(308, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
    String name;
    boolean medCondition;
    int age;
    int priority;
    Integer priorityINT;
        
        vacPatient v = new vacPatient();
        name = pNamTf.getText();
        medCondition = Boolean.valueOf(mConTf.getText());
        age = new Integer(pAgeTf.getText());
        v.setName(name);
        v.setMedCondition(medCondition);
        v.setAge(age);
        
        priorityINT = new Integer (prioTf.getText());
        priority = priorityINT.intValue();
        thePQueue.enqueue(priority,v);

        jTextArea1.append(pNamTf.getText() + " your details have been successfully added to the queue"+ "\n");
        pNamTf.setText("");
        mConTf.setText("");
        pAgeTf.setText("");
        prioTf.setText("");
     
   

    
        
    }//GEN-LAST:event_addBtnActionPerformed

    private void schedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schedBtnActionPerformed
        // TODO add your handling code here:
                if(!thePQueue.isEmpty()){
            PUElement puelem = (PUElement)thePQueue.dequeue();
            vacPatient v1 = (vacPatient)puelem.getElement();
            
            jTextArea1.append("The doctor is now ready to see " + v1.getName());
            jTextArea1.append("  age: " + v1.getAge());
            jTextArea1.append("  medCondition: " + v1.getMedCondition());
            jTextArea1.append("  Priority: " + puelem.getKey()+ "\n");
            
        }
        else
            jTextArea1.append("There are no more patients waiting"+ "\n");
       
       
    }//GEN-LAST:event_schedBtnActionPerformed

    private void extBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extBtnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_extBtnActionPerformed

    private void pListBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pListBtnActionPerformed
        // TODO add your handling code here:
         jTextArea1.append("The patients waiting in the queue...."+ "\n");
        jTextArea1.append(thePQueue.printPQueue()+ "\n");
    }//GEN-LAST:event_pListBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VaccineGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VaccineGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VaccineGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VaccineGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VaccineGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton extBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel mConLbl;
    private javax.swing.JTextField mConTf;
    private javax.swing.JLabel pAgeLbl;
    private javax.swing.JTextField pAgeTf;
    private javax.swing.JButton pListBtn;
    private javax.swing.JLabel pNamLbl;
    private javax.swing.JTextField pNamTf;
    private javax.swing.JLabel prioLbl;
    private javax.swing.JTextField prioTf;
    private javax.swing.JButton schedBtn;
    // End of variables declaration//GEN-END:variables
}
